name: Build

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  kvm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: install build dependencies
        run: sudo apt-get install -y bc fakeroot flex bison libelf-dev libssl-dev ncurses-dev

      - name: copy Ubuntu kernel config
        run: cp /boot/config-$(uname -r) .config
        working-directory: kvm-vmi/kvm

      - name: configure kernel
        run: |
          # disable kernel signature
          ./scripts/config --disable SYSTEM_TRUSTED_KEYS
          ./scripts/config --disable SYSTEM_REVOCATION_KEYS
          # compress debug info (otherwise might fail with 'no space left on device' on the runnner)
          ./scripts/config --enable DEBUG_INFO_COMPRESSED
          # enable KVM
          ./scripts/config --module KVM
          ./scripts/config --module KVM_INTEL
          ./scripts/config --module KVM_AMD
          ./scripts/config --enable KVM_INTROSPECTION
          # tweak locaversion
          ./scripts/config --set-str CONFIG_LOCALVERSION -kvm-vmi
        working-directory: kvm-vmi/kvm

      - name: olddefconfig
        run: make olddefconfig
        working-directory: kvm-vmi/kvm

      - name: generate debian package
        run: make -j$(nproc) bindeb-pkg

      - uses: actions/upload-artifact@v3
        with:
          name: kvm-${{ matrix.os }}
          path: '*.deb'
